"""DOCX export — clinical-grade Word document."""
from io import BytesIO
from typing import Dict, Any
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


TEAL  = RGBColor(0x0E, 0xA5, 0xA4)
NAVY  = RGBColor(0x0B, 0x2A, 0x4A)
MUTED = RGBColor(0x64, 0x74, 0x8B)
TEXT  = RGBColor(0x1E, 0x23, 0x27)


def _set_run(run, *, color=TEXT, bold=False, size=10, font="Calibri"):
    run.font.name = font
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color


def _h1(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    _set_run(r, color=NAVY, bold=True, size=18)
    return p


def _h3(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text.upper())
    _set_run(r, color=TEAL, bold=True, size=10)
    return p


def _body(doc, text, *, muted=False):
    if not text:
        return
    p = doc.add_paragraph()
    r = p.add_run(text)
    _set_run(r, color=MUTED if muted else TEXT, size=10)
    return p


def render_docx(state: Dict[str, Any]) -> bytes:
    doc = Document()
    soap = state.get("soap", {})
    cdt  = state.get("cdt_codes", []) or []

    _h1(doc, "DentaScribe Consultation Note")
    _body(doc,
          f"Patient: {state.get('patient_name','—')}  |  "
          f"Provider: {state.get('doctor_name','—')}  |  "
          f"Date: {state.get('created_at','—')[:19].replace('T',' ')}",
          muted=True)

    for label, key in [
        ("Chief Complaint", "chief_complaint"),
        ("Subjective", "subjective"),
        ("Objective", "objective"),
        ("Dental Examination Findings", "dental_exam"),
        ("Assessment", "assessment"),
        ("Plan", "plan"),
    ]:
        if soap.get(key):
            _h3(doc, label)
            _body(doc, soap[key])

    meds = soap.get("medications") or []
    if meds:
        _h3(doc, "Medications")
        for m in meds:
            _body(doc, f"• {m}")

    if soap.get("follow_up"):
        _h3(doc, "Follow-up")
        _body(doc, soap["follow_up"])

    if cdt:
        _h3(doc, "CDT 2026 Codes (Suggested)")
        table = doc.add_table(rows=1, cols=4)
        table.autofit = True
        hdr = table.rows[0].cells
        for i, (c, w) in enumerate(zip(
            ["Code", "Nomenclature", "Confidence", "Rationale"],
            [0.7, 2.6, 0.8, 2.6]
        )):
            hdr[i].width = Inches(w)
            r = hdr[i].paragraphs[0].add_run(c)
            _set_run(r, color=RGBColor(0xFF, 0xFF, 0xFF), bold=True, size=10)
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
            tcPr = hdr[i]._tc.get_or_add_tcPr()
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear"); shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), "0EA5A4")
            tcPr.append(shd)

        for code in cdt:
            row = table.add_row().cells
            for i, val in enumerate([
                code["code"],
                code["nomenclature"],
                f"{code.get('confidence', 0):.0%}",
                code.get("rationale", ""),
            ]):
                r = row[i].paragraphs[0].add_run(str(val))
                _set_run(r, size=9)

    qa = state.get("qa") or {}
    if qa.get("warnings") or qa.get("unconfirmed_terms"):
        _h3(doc, "Quality Notes (auto-generated)")
        for w in qa.get("warnings", []):
            _body(doc, f"• {w}", muted=True)
        if qa.get("unconfirmed_terms"):
            _body(doc,
                  "Unverified terms (verify against transcript): "
                  + ", ".join(qa["unconfirmed_terms"]),
                  muted=True)

    if soap.get("notes_for_doctor"):
        _h3(doc, "Notes for Doctor")
        _body(doc, soap["notes_for_doctor"])

    _body(doc,
          "Generated by DentaScribe — AI clinical scribe. Review before signing. "
          "CDT codes © American Dental Association.",
          muted=True)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
